version: '3.3'

services:
  # UND devnet services
  mainchain-demonet-node1:
    hostname: mainchain-demonet-node1
    build:
      context: Docker/und_devnet
      dockerfile: validator/Dockerfile
      args:
        SUBNET_IP: ${SUBNET_IP}
        NODE: "node1"
    container_name: mainchain-demonet-node1
    command: /usr/bin/und start --home /root/.und_mainchain/node1 --p2p.laddr=tcp://0.0.0.0:26651 --rpc.laddr=tcp://0.0.0.0:26661 --log_level="main:info,state:info,x/enterprise:debug,x/beacon:debug,x/wrkchain:debug,*:error"
    networks:
      wrkchainnet:
        ipv4_address: ${SUBNET_IP}.3
    ports:
      - "26661:26661"
      - "26651:26651"

  mainchain-demonet-node2:
    hostname: mainchain-demonet-node2
    build:
      context: Docker/und_devnet
      dockerfile: validator/Dockerfile
      args:
        SUBNET_IP: ${SUBNET_IP}
        NODE: "node2"
    container_name: mainchain-demonet-node2
    command: /usr/bin/und start --home /root/.und_mainchain/node2 --p2p.laddr=tcp://0.0.0.0:26652 --rpc.laddr=tcp://0.0.0.0:26662 --log_level="main:info,state:info,x/enterprise:debug,x/beacon:debug,x/wrkchain:debug,*:error"
    networks:
      wrkchainnet:
        ipv4_address: ${SUBNET_IP}.4
    ports:
      - "26662:26662"
      - "26652:26652"

  mainchain-demonet-rest-server:
    hostname: mainchain-demonet-rest-server
    build:
      context: Docker/und_devnet
      dockerfile: validator/Dockerfile
      args:
        SUBNET_IP: ${SUBNET_IP}
        NODE: "node3"
    container_name: mainchain-demonet-rest-server
    command: >
      /bin/sh -c "
        until nc -z ${SUBNET_IP}.3 26661; do sleep 1; echo 'wait for node1'; done
        echo 'wait for first block'
        sleep 10
        /usr/bin/undcli rest-server --laddr=tcp://0.0.0.0:1317 --node tcp://${SUBNET_IP}.3:26661 --chain-id=FUND-Mainchain-DevNet --trust-node=false
      "
    networks:
      wrkchainnet:
        ipv4_address: ${SUBNET_IP}.6
    ports:
      - "1317:1317"

  mainchain-demonet-proxy:
    hostname: mainchain-demonet-proxy
    build:
      context: Docker/und_devnet
      dockerfile: proxy/Dockerfile
      args:
        REST_IP: ${SUBNET_IP}.6
    container_name: mainchain-demonet-proxy
    networks:
      wrkchainnet:
        ipv4_address: ${SUBNET_IP}.7
    ports:
      - "1318:1318"

  mainchain-demonet-explorer:
    hostname: mainchain-demonet-explorer
    build:
      context: Docker/und_devnet
      dockerfile: explorer/Dockerfile
      args:
        RPC: "${SUBNET_IP}.3:26661"
        LCD: "${SUBNET_IP}.7:1318"
    container_name: mainchain-demonet-explorer
    command: meteor --settings devnet_settings.json
    networks:
      wrkchainnet:
        ipv4_address: ${SUBNET_IP}.8
    ports:
      - 3000:3000

#  # WRKChain Services
  finchain-rpc:
    depends_on:
      - finchain-validator-1
    build:
      args:
        GO_VERSION: 13.1
        PRIVATE_KEY: 5d0929559ea34a21cfece4183400ebfbb049f7c8a7cb251b61a4b6cde399ef42 #0x36D82EeF3Ce9897b0073116F29E28F6E149757d0
        WALLET_PASS: pass
        WRKCHAIN_DATA_DIR: .und_wrkchain
        SUBNET_IP: ${SUBNET_IP}
      context: Docker/wrkchain
      dockerfile: node/Dockerfile
    command: /src/go-ethereum/build/bin/geth --datadir=/root/.und_wrkchain --networkid 2339117895
      --nodekey="/root/.und_wrkchain/node_keys/0x36D82EeF3Ce9897b0073116F29E28F6E149757d0.key"
      --port 30308 --http --http.addr "0.0.0.0" --http.api "admin,debug,eth,net,personal,txpool,web3"
      --http.corsdomain "*" --http.port "8547" --http.vhosts "*" --syncmode=full --verbosity=3 --nodiscover
    container_name: finchain-rpc
    expose:
    - 8547
    hostname: finchain-rpc
    networks:
      wrkchainnet:
        ipv4_address: ${SUBNET_IP}.25
    ports:
      - 8547:8547
      - 30308:30308
  finchain-validator-1:
    build:
      args:
        GO_VERSION: 13.1
        PRIVATE_KEY: 62eff7207e271faea97fe8d2d7ae12093c7cfe43b9e20ffd57232bf42f5cc899 #0x6C45443De823a45e8f7204F1E69428E9AB42dd08
        WALLET_PASS: pass
        WRKCHAIN_DATA_DIR: .und_wrkchain
        SUBNET_IP: ${SUBNET_IP}
      context: Docker/wrkchain
      dockerfile: node/Dockerfile
    command: /src/go-ethereum/build/bin/geth --datadir=/root/.und_wrkchain --etherbase 0x6C45443De823a45e8f7204F1E69428E9AB42dd08
      --gasprice 0 --mine --networkid 2339117895 --nodekey="/root/.und_wrkchain/node_keys/0x6C45443De823a45e8f7204F1E69428E9AB42dd08.key"
      --nodiscover --password /root/.walletpassword --port 30306 --syncmode=full --unlock
      0x6C45443De823a45e8f7204F1E69428E9AB42dd08 --verbosity=4 --nodiscover
    container_name: finchain-validator-1
    expose:
    - 30306
    hostname: finchain-validator-1
    networks:
      wrkchainnet:
        ipv4_address: ${SUBNET_IP}.23
    ports:
    - published: 30306
      target: 30306
  finchain-validator-2:
    build:
      args:
        GO_VERSION: 13.1
        PRIVATE_KEY: 226cd6688ec379ef14ae04e9893e96c9adc612bd4f5360d2cb3c4380f9fa612c #0x743454EE5c097E56D0470C09B6c23880356Ce5FB
        WALLET_PASS: pass
        WRKCHAIN_DATA_DIR: .und_wrkchain
        SUBNET_IP: ${SUBNET_IP}
      context: Docker/wrkchain
      dockerfile: node/Dockerfile
    command: /src/go-ethereum/build/bin/geth --datadir=/root/.und_wrkchain --etherbase 0x743454EE5c097E56D0470C09B6c23880356Ce5FB
      --gasprice 0 --mine --networkid 2339117895 --nodekey="/root/.und_wrkchain/node_keys/0x743454EE5c097E56D0470C09B6c23880356Ce5FB.key"
      --nodiscover --password /root/.walletpassword --port 30307 --syncmode=full --unlock
      0x743454EE5c097E56D0470C09B6c23880356Ce5FB --verbosity=4 --nodiscover
    container_name: finchain-validator-2
    expose:
    - 30307
    hostname: finchain-validator-2
    networks:
      wrkchainnet:
        ipv4_address: ${SUBNET_IP}.24
    ports:
    - published: 30307
      target: 30307
  finchain-explorer:
    hostname: finchain-explorer
    depends_on:
      - finchain-rpc
    ports:
      - 8081:8081
    build:
      context: Docker/wrkchain
      dockerfile: explorer/Dockerfile
      args:
        wrkchain_rpc: "${SUBNET_IP}.25:8547"
    container_name: finchain-explorer
    expose:
      - 8081
    networks:
      wrkchainnet:
        ipv4_address: ${SUBNET_IP}.26
  finchain-wrkoracle:
    hostname: finchain-wrkoracle
    depends_on:
      - finchain-rpc
    build:
      context: Docker/wrkchain
      dockerfile: wrkoracle/Dockerfile
      args:
        SUBNET_IP: ${SUBNET_IP}
    command: /root/src/run-wrkoracle.sh ${SUBNET_IP}.3:26661
    container_name: finchain-wrkoracle
    networks:
      wrkchainnet:
        ipv4_address: ${SUBNET_IP}.27
  finchain-ui:
    hostname: finchain-ui
    depends_on:
      - finchain-rpc
    ports:
      - 4040:4040
    build:
      context: Docker/wrkchain
      dockerfile: wrkchain_validator_ui/Dockerfile
      args:
        MAINCHAIN_EXPLORER_URL: "http://localhost:3000"
        MAINCHAIN_REST_URL: "http://localhost:1318"
        WRKCHAIN_EXPLORER_URL: "http://localhost:8081"
        WRKCHAIN_NAME: ${WRKCHAIN_NAME}
        WRKCHAIN_NETWORK_ID: 2339117895
        WRKCHAIN_ID: 1
        WRKCHAIN_OWNER: "und1x8pl6wzqf9atkm77ymc5vn5dnpl5xytmn200xy"
        WRKCHAIN_WRITE_TIMEOUT: 60
        WRKCHAIN_WEB3_PROVIDER_URL: "http://${SUBNET_IP}.25:8547"
        WRKCHAIN_RPC_HOST: "${SUBNET_IP}.25"
        WRKCHAIN_RPC_PORT: 8547
        WRKCHAIN_VALIDATOR_SERVICE_PORT: 4040
        ALPHAVANTAGE: ${ALPHAVANTAGE}
        WORLDTRADING: ${WORLDTRADING}
        IEX: ${IEX}
        THRESHOLD: ${THRESHOLD}
        CRYPTO_THRESHOLD: ${CRYPTO_THRESHOLD}
        CRYPTO_TIMEDIFF: ${CRYPTO_TIMEDIFF}
        TRACKED_TICKERS: ${TRACKED_TICKERS}
        UPDATE_TIME: ${UPDATE_TIME}
        CRYPTO_UPDATE_TIME: ${CRYPTO_UPDATE_TIME}
        MNEMONIC: ${MNEMONIC}
    container_name: finchain-ui
    expose:
      - 4040
    networks:
      wrkchainnet:
        ipv4_address: ${SUBNET_IP}.28

networks:
  wrkchainnet:
    driver: bridge
    ipam:
      config:
      - subnet: ${SUBNET_IP}.0/24