version: '3.3'

services:
  # UND devnet services
  mainchain-dev-validator-1:
    hostname: mainchain-dev-validator-1
    build:
      context: Docker/und_devnet
      dockerfile: validator/Dockerfile
      args:
        privatekey: 62eff7207e271faea97fe8d2d7ae12093c7cfe43b9e20ffd57232bf42f5cc899
        password: pass
    container_name: mainchain-dev-validator-1
    command: /root/.go/bin/und --verbosity 4 --datadir /root/.und_mainchain --identity "mainchain-dev-validator-1" --password /root/.accountpassword --networkid 50010 --port 30401 --mine --gasprice "1" --targetgaslimit "420000000" --etherbase "0x6C45443De823a45e8f7204F1E69428E9AB42dd08" --unlock "0x6C45443De823a45e8f7204F1E69428E9AB42dd08" --syncmode="full" --nodekey="/root/.und_mainchain/bootnode_keys/0x6C45443De823a45e8f7204F1E69428E9AB42dd08.key" --nodiscover
    ports:
      - 30401:30401/tcp
    expose:
      - 30401
    networks:
      wrkchainnet:
        ipv4_address: 172.25.1.2

  mainchain-dev-validator-2:
    hostname: mainchain-dev-validator-2
    build:
      context: Docker/und_devnet
      dockerfile: validator/Dockerfile
      args:
        privatekey: 226cd6688ec379ef14ae04e9893e96c9adc612bd4f5360d2cb3c4380f9fa612c
        password: word
    container_name: mainchain-dev-validator-2
    command: /root/.go/bin/und --verbosity 4 --datadir /root/.und_mainchain --identity "mainchain-dev-validator-2" --password /root/.accountpassword --networkid 50010 --port 30402 --mine --gasprice "1" --targetgaslimit "420000000" --etherbase "0x743454EE5c097E56D0470C09B6c23880356Ce5FB" --unlock "0x743454EE5c097E56D0470C09B6c23880356Ce5FB" --syncmode="full" --nodekey="/root/.und_mainchain/bootnode_keys/0x743454EE5c097E56D0470C09B6c23880356Ce5FB.key" --nodiscover
    ports:
      - 30402:30402/tcp
    expose:
      - 30402
    networks:
      wrkchainnet:
        ipv4_address: 172.25.1.3

  mainchain-dev-validator-3:
    hostname: mainchain-dev-validator-3
    build:
      context: Docker/und_devnet
      dockerfile: validator/Dockerfile
      args:
        privatekey: 5d0929559ea34a21cfece4183400ebfbb049f7c8a7cb251b61a4b6cde399ef42
        password: word
    container_name: mainchain-dev-validator-3
    command: /root/.go/bin/und --verbosity 4 --datadir /root/.und_mainchain --identity "mainchain-dev-validator-3" --password /root/.accountpassword --networkid 50010 --port 30403 --mine --gasprice "1" --targetgaslimit "420000000" --etherbase "0x36D82EeF3Ce9897b0073116F29E28F6E149757d0" --unlock "0x36D82EeF3Ce9897b0073116F29E28F6E149757d0" --syncmode="full" --nodekey="/root/.und_mainchain/bootnode_keys/0x36D82EeF3Ce9897b0073116F29E28F6E149757d0.key" --nodiscover
    ports:
      - 30403:30403/tcp
    expose:
      - 30403
    networks:
      wrkchainnet:
        ipv4_address: 172.25.1.4

  mainchain-dev-rpc:
    hostname: mainchain-dev-rpc
    build:
      context: Docker/und_devnet
      dockerfile: validator/Dockerfile
      args:
        privatekey: 5c7d979c27680c498c0b3b2a00ef318097a7567b15f3a6a3fa1393b9da301a14
        password: word
    container_name: mainchain-dev-rpc
    command: /root/.go/bin/und --verbosity 4 --datadir /root/.und_mainchain --identity "mainchain-rpc" --networkid 50010 --port 30404 --rpc --rpccorsdomain "*" --rpcaddr 0.0.0.0 --rpcport 8101 --rpcvhosts "*" --ws --wsaddr 0.0.0.0 --wsport 8111 --wsorigins "*" --syncmode="full" --nodiscover
    ports:
      - 30404:30404/tcp
      - 8101:8101/tcp
      - 8111:8111/tcp
    expose:
      - 30404
      - 8101
      - 8111
    networks:
      wrkchainnet:
        ipv4_address: 172.25.1.5

  mainchain-dev-explorer:
    hostname: mainchain-dev-explorer
    depends_on:
      - mainchain-dev-rpc
    ports:
      - 8080:8080
    build:
      context: Docker/und_devnet
      dockerfile: explorer/Dockerfile
      args:
        mainchain_rpc: "172.25.1.5:8101"
    container_name: mainchain-dev-explorer
    expose:
      - 8080
    networks:
      wrkchainnet:
        ipv4_address: 172.25.1.6

  # WRKChain Services
  finchain-rpc:
    depends_on:
      - finchain-validator-1
    build:
      args:
        GO_VERSION: 10.3
        PRIVATE_KEY: 5d0929559ea34a21cfece4183400ebfbb049f7c8a7cb251b61a4b6cde399ef42
        WALLET_PASS: pass
        WRKCHAIN_DATA_DIR: .und_wrkchain
      context: Docker/wrkchain
      dockerfile: node/Dockerfile
    command: /root/.go/bin/geth --datadir=/root/.und_wrkchain --networkid 2339117895
      --nodekey="/root/.und_wrkchain/node_keys/0x36D82EeF3Ce9897b0073116F29E28F6E149757d0.key"
      --port 30308 --rpc --rpcaddr "0.0.0.0" --rpcapi "admin,db,debug,eth,net,personal,txpool,web3"
      --rpccorsdomain "*" --rpcport "8547" --rpcvhosts "*" --syncmode=full --verbosity=3 --nodiscover
    container_name: finchain-rpc
    expose:
    - 8547
    hostname: finchain-rpc
    networks:
      wrkchainnet:
        ipv4_address: 172.25.1.25
    ports:
    - published: 8547
      target: 8547
  finchain-validator-1:
    build:
      args:
        GO_VERSION: 10.3
        PRIVATE_KEY: 62eff7207e271faea97fe8d2d7ae12093c7cfe43b9e20ffd57232bf42f5cc899
        WALLET_PASS: pass
        WRKCHAIN_DATA_DIR: .und_wrkchain
      context: Docker/wrkchain
      dockerfile: node/Dockerfile
    command: /root/.go/bin/geth --datadir=/root/.und_wrkchain --etherbase 0x6C45443De823a45e8f7204F1E69428E9AB42dd08
      --gasprice 0 --mine --networkid 2339117895 --nodekey="/root/.und_wrkchain/node_keys/0x6C45443De823a45e8f7204F1E69428E9AB42dd08.key"
      --nodiscover --password /root/.walletpassword --port 30306 --syncmode=full --unlock
      0x6C45443De823a45e8f7204F1E69428E9AB42dd08 --verbosity=4 --nodiscover
    container_name: finchain-validator-1
    expose:
    - 30306
    hostname: finchain-validator-1
    networks:
      wrkchainnet:
        ipv4_address: 172.25.1.23
    ports:
    - published: 30306
      target: 30306
  finchain-validator-2:
    build:
      args:
        GO_VERSION: 10.3
        PRIVATE_KEY: 226cd6688ec379ef14ae04e9893e96c9adc612bd4f5360d2cb3c4380f9fa612c
        WALLET_PASS: pass
        WRKCHAIN_DATA_DIR: .und_wrkchain
      context: Docker/wrkchain
      dockerfile: node/Dockerfile
    command: /root/.go/bin/geth --datadir=/root/.und_wrkchain --etherbase 0x743454EE5c097E56D0470C09B6c23880356Ce5FB
      --gasprice 0 --mine --networkid 2339117895 --nodekey="/root/.und_wrkchain/node_keys/0x743454EE5c097E56D0470C09B6c23880356Ce5FB.key"
      --nodiscover --password /root/.walletpassword --port 30307 --syncmode=full --unlock
      0x743454EE5c097E56D0470C09B6c23880356Ce5FB --verbosity=4 --nodiscover
    container_name: finchain-validator-2
    expose:
    - 30307
    hostname: finchain-validator-2
    networks:
      wrkchainnet:
        ipv4_address: 172.25.1.24
    ports:
    - published: 30307
      target: 30307
  finchain-explorer:
    hostname: finchain-explorer
    depends_on:
      - finchain-rpc
    ports:
      - 8081:8081
    build:
      context: Docker/wrkchain
      dockerfile: explorer/Dockerfile
      args:
        wrkchain_rpc: "172.25.1.25:8547"
    container_name: finchain-explorer
    expose:
      - 8081
    networks:
      wrkchainnet:
        ipv4_address: 172.25.1.26
  finchain-wrkoracle:
    hostname: finchain-wrkoracle
    depends_on:
      - finchain-rpc
    build:
      context: Docker/wrkchain
      dockerfile: wrkoracle/Dockerfile
      args:
        PRIVATE_KEY: cbb3de0ea413043e7ae615115e01d3435a7e2d66728f6739006fa5fe95e69898
        WALLET_PASS: pass
    command: /root/src/run-wrkoracle.sh
    container_name: finchain-wrkoracle
    networks:
      wrkchainnet:
        ipv4_address: 172.25.1.27
  finchain-validator-ui:
    hostname: finchain-validator-ui
    depends_on:
      - finchain-rpc
    ports:
      - 4040:4040
    build:
      context: Docker/wrkchain
      dockerfile: wrkchain_validator_ui/Dockerfile
    container_name: finchain-validator-ui
    expose:
      - 4040
    networks:
      wrkchainnet:
        ipv4_address: 172.25.1.28

networks:
  wrkchainnet:
    driver: bridge
    ipam:
      config:
      - subnet: 172.25.1.0/24